# TCL File Generated by Component Editor 9.0
# Wed Apr 07 13:17:02 YEKST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | M4KWriter "M4KWriter" v1.0
# | null 2010.04.07.13:17:02
# | 
# | 
# +-----------------------------------


# +-----------------------------------
# | module M4KWriter
# | 
set_module_property NAME M4KWriter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Interfaces
set_module_property DISPLAY_NAME M4KWriter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave holdTime 1
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 1
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitStates 2
set_interface_property avalon_slave writeWaitTime 2

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave Data writedata Input 32
add_interface_port avalon_slave WR write Input 1
add_interface_port avalon_slave Address address Input 9
# | 
# +-----------------------------------
