# TCL File Generated by Component Editor 9.0
# Mon Sep 20 17:41:15 YEKST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | RD_D32_A9 "RD_D32_A9" v1.0
# | null 2010.09.20.17:41:15
# | 
# | 
# +-----------------------------------


# +-----------------------------------
# | module RD_D32_A9
# | 
set_module_property NAME RD_D32_A9
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Interfaces
set_module_property DISPLAY_NAME RD_D32_A9
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave holdTime 1
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 1
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 1
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitStates 1
set_interface_property avalon_slave writeWaitTime 1

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_sink
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave RData readdata Output 32
add_interface_port avalon_slave RD read Input 1
add_interface_port avalon_slave Address address Input 9
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

set_interface_property clock_sink ENABLED true
# | 
# +-----------------------------------
